FROM php:8.1-cli

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем необходимые зависимости для работы с PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Устанавливаем Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Копируем все файлы проекта в контейнер
COPY . /app

# Устанавливаем зависимости с помощью Composer
RUN composer install --no-dev --optimize-autoloader

# Указываем команду для запуска WebSocket сервера
CMD ["php", "public/ws-server.php"]

# Открываем порт 9090 для WebSocket
EXPOSE 9090
